name: Repository list

on:
  workflow_dispatch:

jobs:
  repo-list:
    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v2
    - name: Get orgs
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GH_EA_TOKEN}}
        script: |
          fs = require('fs')

          const query = `query($enterpriseName:String!, $cursor:String) {
            enterprise(slug: $enterpriseName) {
              name
              organizations(first: 100, after: $cursor) {
                pageInfo {
                  hasNextPage
                  endCursor
                }
                totalCount
                nodes {
                  name 
                  login
                }
              }
            }
          }`;
          const variables = {
            enterpriseName: 'octodemo'
          }
          const result = await github.graphql(query, variables)
          fs.writeFileSync('orgs.json', JSON.stringify(result.nodes))
          console.log(result)
    - name: Save the orgs
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "latest list of orgs"
          git push