name: Repository list

on:
  workflow_dispatch:

jobs:
  repo-list:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Get orgs
      uses: helaili/ea-repo-list@master
      with:
        enterprise: octodemo
        outputFilename: orgs.json
        token: ${{secrets.GH_EA_TOKEN}}
    - name: Save the orgs
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "latest list of orgs"
          git push