name: Generate repository list

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *' # Every hour

env:
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}   
  
jobs:
  repo-list:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Get the repos
      uses: helaili/ea-repo-list@master
      with:
        enterprise: Ramboll
        outputFilename: repositories.json
#        token: ${{secrets.GITHUB_TOKEN}}
    - name: Save the repos
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "latest list of repos"
          git push
